import type {Project} from "@/data/projects";
import {ArrowUpRight,Layers3} from "lucide-react";
export function ProjectCard({project}:{project:Project}){
 return <a href={"/projets/"+project.slug} className="group block overflow-hidden rounded-3xl border border-white/10 bg-[#101010] transition duration-500 hover:-translate-y-1 hover:border-white/20 hover:shadow-[0_24px_80px_rgba(0,0,0,.35)]">
  <div className="orange-gradient relative aspect-[16/10] overflow-hidden"><div className="absolute inset-5 rounded-2xl border border-white/10 bg-black/55 p-3 shadow-2xl backdrop-blur-sm transition duration-500 group-hover:scale-[1.025] group-hover:-rotate-[.35deg]">
   <div className="flex h-full items-center justify-center rounded-xl border border-white/10 bg-gradient-to-br from-white/[.06] to-transparent"><div className="w-[76%] rounded-xl border border-white/10 bg-[#151515] p-3 shadow-glow">
    <div className="mb-3 flex items-center justify-between"><div className="flex gap-1"><span className="h-1.5 w-1.5 rounded-full bg-white/25"/><span className="h-1.5 w-1.5 rounded-full bg-white/15"/><span className="h-1.5 w-1.5 rounded-full bg-white/10"/></div><Layers3 size={12} className="text-white/20"/></div>
    <div className="h-2 w-1/2 rounded-full bg-white/10"/><div className="mt-2 h-8 w-full rounded-lg" style={{background:"linear-gradient(135deg, "+project.accent+"55, transparent)"}}/><div className="mt-2 grid grid-cols-3 gap-2"><span className="h-10 rounded-md bg-white/[.05]"/><span className="h-10 rounded-md bg-white/[.05]"/><span className="h-10 rounded-md bg-white/[.05]"/></div>
   </div></div></div><span className="absolute right-4 top-4 rounded-full border border-white/10 bg-black/50 px-3 py-1 text-[11px] text-white/70 backdrop-blur">{project.status}</span><span className="absolute bottom-4 left-4 rounded-full border border-white/10 bg-black/45 px-3 py-1 text-[11px] text-white/50 backdrop-blur">Voir le projet</span></div>
  <div className="p-5 md:p-6"><div className="mb-2 text-xs font-semibold uppercase tracking-[.18em]" style={{color:project.accent}}>{project.category}</div><div className="flex items-start justify-between gap-4"><div><h3 className="text-xl font-bold">{project.name}</h3><p className="mt-2 max-w-md text-sm leading-6 text-white/55">{project.description}</p></div><span className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-white/10 transition duration-300 group-hover:border-orange group-hover:bg-orange group-hover:text-black"><ArrowUpRight size={17}/></span></div><div className="mt-5 flex flex-wrap gap-2">{project.stack.map(tech=><span key={tech} className="rounded-full bg-white/[.05] px-2.5 py-1 text-[11px] text-white/55">{tech}</span>)}</div></div>
 </a>
}